version: '3'

vars:
  APP: fibber
  MAIN: ./cmd/fibber
  OUT: bin/{{.APP}}
  VERSION: '{{sh "git describe --tags --always --dirty"}}'
  COMMIT: '{{sh "git rev-parse HEAD"}}'
  BUILDTIME: '{{sh "date -u +%Y-%m-%dT%H:%M:%SZ"}}'
  LDFLAGS: >-
    -X main.Version={{.VERSION}}
    -X main.Commit={{.COMMIT}}
    -X main.BuildTime={{.BUILDTIME}}

tasks:
  build:
    desc: Build the CLI with version info
    cmds:
      - mkdir -p bin
      - go build -ldflags "{{.LDFLAGS}}" -o {{.OUT}} {{.MAIN}}
    sources:
      - "**/*.go"
    generates:
      - "{{.OUT}}"

  run:
    desc: Run the app
    cmds:
      - go run {{.MAIN}} {{.CLI_ARGS}}
    silent: true

  clean:
    desc: Clean the bin directory
    cmds:
      - rm -rf bin

  version:
    desc: Show build version metadata
    cmds:
      - echo "Version:  {{.VERSION}}"
      - echo "Commit:   {{.COMMIT}}"
      - echo "Built at: {{.BUILDTIME}}"